modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="mcse"
version="0.1.3"
displayName="MCv2"
credits="Created using MCreator.net"
displayURL="https://mcreator.net"
authors="CubeUltm"
description='''
Modern Minecraft for Java 8.
'''

[[dependencies.mcse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




